import 'app/globals.css'
import { Inter } from 'next/font/google'
import React from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { GITHUB_URL, ON_POLKADOT_URL } from '@/constants'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Playgrounds',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          
          {children}
        </main>
      </body>
    </html>
  )
}
