import 'app/globals.css'
import { Inter } from 'next/font/google'
import React from 'react'
import Image from 'next/image'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Playgrounds',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <header className="flex flex-row justify-between mx-[72px] mt-[42px] h-14">
            <div className="flex gap-5">
              <div className='w-11 h-11'>
                <Image
                  src="/Logo Solo.svg"
                  alt=''
                  width={42}
                  height={42}
                />
              </div>
              <div className="flex text-2xl text-[#333333] mt-4">
                Cybros Playground
              </div>
            </div>
            <div className='flex justify-between gap-9 ml-16 mr-auto mt-6'>
              <Link href='/'>
                <div className="text-lg leading-[21px] text-[#333333]">
                  NFT Renderer Demo
                </div>
              </Link>
              <Link href='/'>
                <div className="text-lg leading-[21px] text-[#333333]">
                  Broadcast Demo
                </div>
              </Link>
              <Link href='/'>
                <div className="text-lg leading-[21px] text-[#333333] ">
                  Faucet
                </div>
              </Link>
              <Link href='/'>
                <div className="ttext-lg leading-[21px] text-[#333333]">
                  Github
                </div>
              </Link>
              <Link href='/'>
                <div className="text-lg leading-[21px] text-[#333333]">
                  Polkadot.js
                </div>
              </Link>

            </div>
            <div className="border-solid border-[#828282] border-2 rounded-lg bg-white flex flex-row justify-center mt-2 gap-3 w-48 h-12 items-center">
              <Image
                src="/wallet-icon.svg"
                alt=''
                width={21}
                height={21}
              />
              <div className="font-medium leading-[21px] text-[#333333]">
                Connect Wallet
              </div>
            </div>
          </header>
          {children}
        </main>
      </body>
    </html>
  )
}
